
import contextlib
import io
import json
from unittest.mock import patch

import pytest

import main


# ---------------------------------------------------------
# Mock AWS Code Interpreter
# ---------------------------------------------------------

class MockCodeSession:
    """Execute the generated discount calculation locally."""

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        return False

    def invoke(self, operation, payload):
        assert operation == "executeCode"
        assert payload["language"] == "python"
        assert payload["clearContext"] is True

        # Capture the output of the actual code generated by the tool.
        output = io.StringIO()

        with contextlib.redirect_stdout(output):
            exec(payload["code"], {"__builtins__": __builtins__})

            return {
                "stream": [
                    {
                        "result": {
                            "structuredContent": {
                                "stdout": output.getvalue()
                            }
                        }
                    }
                ]
            }


def invoke_discount(
    loyalty_points,
    tier,
    order_total,
    product_category="standard",
):
    """Run the actual decorated function with a mocked interpreter."""

    with patch.object(
        main,
        "code_session",
        return_value=MockCodeSession(),
    ):
        result = main.calculate_loyalty_discount.__wrapped__(
            loyalty_points=loyalty_points,
            tier=tier,
            order_total=order_total,
            product_category=product_category,
        )

        return json.loads(result)

    # ---------------------------------------------------------
    # Test 1: Gold loyalty discount
    # ---------------------------------------------------------


def test_gold_tier_discount():
    result = invoke_discount(
        loyalty_points=4250,
        tier="Gold",
        order_total=150.0,
        product_category="standard",
    )

    assert result["points_redeemed"] == 4000
    assert result["points_discount"] == 40.0
    assert result["tier_discount_pct"] == 10.0
    assert result["tier_discount"] == 11.0
    assert result["final_total"] == 99.0
    assert result["total_savings"] == 51.0
    assert result["points_earned"] == 99
    assert result["remaining_points"] == 349

    # ---------------------------------------------------------
    # Test 2: Redemption cannot exceed 50% of order
    # ---------------------------------------------------------


def test_points_redemption_cap():
    result = invoke_discount(
        loyalty_points=10000,
        tier="Silver",
        order_total=100.0,
    )

    assert result["points_redeemed"] == 5000
    assert result["points_discount"] == 50.0
    assert result["final_total"] == 50.0

    # ---------------------------------------------------------
    # Test 3: Points below 500 cannot be redeemed
    # ---------------------------------------------------------


def test_minimum_redemption():
    result = invoke_discount(
        loyalty_points=450,
        tier="Silver",
        order_total=100.0,
    )

    assert result["points_redeemed"] == 0
    assert result["points_discount"] == 0.0
    assert result["final_total"] == 100.0

    # ---------------------------------------------------------
    # Test 4: Platinum tier discount
    # ---------------------------------------------------------


def test_platinum_tier_discount():
    result = invoke_discount(
        loyalty_points=0,
        tier="Platinum",
        order_total=200.0,
    )

    assert result["tier_discount_pct"] == 15.0
    assert result["tier_discount"] == 30.0
    assert result["final_total"] == 170.0

    # ---------------------------------------------------------
    # Test 5: Product category earning rate
    # ---------------------------------------------------------


@pytest.mark.parametrize(
    "category, expected_rate, expected_points",
    [
        ("standard", 1, 100),
        ("device", 2, 200),
        ("fresh", 5, 500),
    ],
)
def test_product_category_earning_rates(
    category,
    expected_rate,
    expected_points,
):
    result = invoke_discount(
        loyalty_points=0,
        tier="Silver",
        order_total=100.0,
        product_category=category,
    )

    assert result["earn_rate"] == expected_rate
    assert result["points_earned"] == expected_points
    # ---------------------------------------------------------
    # Test 6: Code Interpreter unavailable
    # ---------------------------------------------------------


def test_code_interpreter_fallback():
    with patch.object(
        main,
        "code_session",
        side_effect=RuntimeError("Code Interpreter unavailable"),
    ):
        result = main.calculate_loyalty_discount.__wrapped__(
            loyalty_points=4250,
            tier="Gold",
            order_total=150.0,
            product_category="standard",
        )

        result = json.loads(result)

        assert result["fallback"] is True
        assert result["tier_discount_pct"] == 10.0
        assert result["tier_discount"] == 15.0
        assert result["final_total"] == 135.0

        assert "points_redeemed" not in result

        # ---------------------------------------------------------
        # Test 7: Required output fields
        # ---------------------------------------------------------


def test_required_output_fields():
    result = invoke_discount(
        loyalty_points=4250,
        tier="Gold",
        order_total=150.0,
    )

    required_fields = {
        "points_redeemed",
        "tier_discount_pct",
        "final_total",
        "remaining_points",
    }

    assert required_fields.issubset(result.keys())
